### ISSUE TITLE
Administration mangler tilpasning til 1.6

### ISSUE THREAD

**Issue by mortenborg** [ePay/prestashop#1]
Lige et lille ønske til når I alligevel har fat i det næste gang:

Det virker fint med version 1.6 - tak for det :)

Men inde i ordre administrationen mangler der er lille visuel opdatering så der kommer en kasse rundt om ePay funktionen. Lige nu mangler den og det ser derfor lidt rodet ud.

**Comment by sorenla** [comment]
Gammelt issue, men ePay panelet i ordre administrationen har fået en overhaling per [seneste release](https://github.com/ePay/prestashop/releases/latest) så integrationen visuelt er mere i tråd med den resterende administration.
