### ISSUE TITLE
Problem med double ordre

### ISSUE THREAD

**Issue by freaky250197** [ePay/prestashop#10]
Hej,

Vi har oplevet et problem hvor vi får 2 ordre på samme betaling.

Da både epay og kunden kalder validation kan dette ske når de gør det i samme sekund, for så vil de komme forbi OrderExists(). da ordren ikke på da værende tidspunkt ikke findes, men dog er den også ved at blive oprettet af kunden/epay callback, afhængig af hvem der kalder først.

Vi har oplevet dette problem siden 07-07-2016.

**Comment by Casper-O** [comment]
Hvilken version af Prestashop kører i med?

Er bestillingerne helt identiske, eller er produkterne delt over de 2 ordre?

Hvis produkterne er delt over 2 ordre, er det fordi i har aktiveret "Forsinket forsendelse". Dette kan deaktiveres i 1.6 under "indstillinger -> Ordre"

**Comment by freaky250197** [comment]
Ordrene er totalt identiske pånær ordre nummer, (de bruger samme kurv).

Vi køre med version 4.6, men jeg har sammenlignet den med den nyeste version, og selve måden den verificere på ser ud til at være den samme.

**Comment by Casper-O** [comment]
Jeg tænkte på Prestashop version, ikke modul versionen :) nyeste er fx 1.6.1.6

Midt bedste bud er forsat at forsinket levering er aktiveret da den tillader flere ordre til en cart

**Comment by freaky250197** [comment]
Vi køre prestashop version .

Vi har ikke forsinket levering slået til. Vi kan se i vores access log at de to requests kommer fuldkommen på samme tid, så problemet er at når de tjeker om, der findes en ordre med dette card id får de begge false, da de kalder på samme tid. Og derfor opretter de også begge en ny ordre på samme cart, og samme betaling.

**Comment by Casper-O** [comment]
Okay, det lyder mystisk og ikke et problem jeg har oplevet - nu har vi så vidt jeg husker også sprunget 1.6.1.4 over pga andre issues med den version.

prøv evt at fjerne denne parameter og se om det løser jeres problem:
https://github.com/ePay/prestashop/blob/master/epay/epay.php#L923

**Comment by freaky250197** [comment]
Men så vil ePay vel aldrig lave et callback? Vi har situationer hvor kunden ikke selv kommer tilbage på validation siden.

Vil der ikke være en måde hvor man i ePay kan sætte et delay på hvornår ePay skal kalde vores server? (F.eks. 5 minutter efter købet)

**Comment by storkie** [comment]
@freaky250197 Det er korrekt, så vil I aldrig modtage callback.

Jeg vil anbefale, at I udelukkende opretter en ordre, hvis callback er modtaget.
Det kan gøres ved at rette
https://github.com/ePay/prestashop/blob/master/epay/controllers/front/validation.php#L57
fra
`if($this->module->validateOrder((int)$id_cart, Configuration::get('PS_OS_PAYMENT'), $total, $this->module->displayName, $message, $mailVars, null, false, $cart->secure_key))
`
til
`if(Tools::getValue('callback') == "1" && $this->module->validateOrder((int)$id_cart, Configuration::get('PS_OS_PAYMENT'), $total, $this->module->displayName, $message, $mailVars, null, false, $cart->secure_key))`

**Comment by Casper-O** [comment]
> Vi har situationer hvor kunden ikke selv kommer tilbage på validation siden.

Til at starte med nævner i ellers at både kunde og epay laver callback på samme tid og derved oprettes en dobbelt ordre - Derfor mit forslag om at fjerne callback, selvom det ikke er det smarteste. Jeg har forsøgt at genskabe jeres fejl og kan ikke umiddelbart lade sig gøre, desværre

**Comment by storkie** [comment]
@Casper-O Kunden/kortholder laver aldrig callback. Her er der tale om en redirect i browseren. Den kan man som udgangspunkt aldrig stole på nogensinde sker. Callback er altid garanteret, da det er server-server kald.
Ved at fjerne callback er der derfor ingen garanti for at besked om gennemført betaling modtages.

**Comment by Casper-O** [comment]
@storkie du har helt ret :+1: . Godt at se dig her inde igen

**Comment by osos** [comment]
Vi oplever desværre det samme problem af og til, på trods af, at der, jf. logfilen kan være adskillige sekunder imellem kunde/epay callback.

@storkie, jeg ville dog nok ændre https://github.com/ePay/prestashop/blob/master/epay/controllers/front/validation.php#L53 i stedet. Men mindre væsentligt.

Vi bruger også pull #8 , som betydeligt forbedrer informationen i backoffice på validate.

**Comment by sorenla** [comment]
Problematikken med dobbel ordrer er løst per version 4.9.0 af ePay modulet. 

Vi opfordrer til at hente [seneste release](https://github.com/ePay/prestashop/releases/latest)
