### ISSUE TITLE
Implement bootstrap grid columns

### ISSUE THREAD

**Issue by ebbesmoeller** [ePay/prestashop#13]
In the function 'displayTransactionForm()' in the main class, the string should contain an extra div with classes defining grid size. As it is now, the panel on order pages in the backoffice overflows other panels, because a grid size is not defined.

Proposed is adding following as an extra line on line 693, and closing this div on line 820/821.

`<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">`

**Comment by AllanWLie** [comment]
Hi @ebbesmoeller 

We are not experiencing the issue you have. If I implement your solution, and resize the browser window then a our panel get overflowed by a large white panel.

**Comment by ebbesmoeller** [comment]
That seems weird. That is the exact problem we have when not applying my beforementioned solution.What version of PS is this on?

**Comment by AllanWLie** [comment]
We have tested it on 1.6.17 and 1.7.x

**Comment by ebbesmoeller** [comment]
We're currently on version 1.6.0.5.
I've digged further through this. It seems that the problem arises when other modules using the same hook, uses bootstrap grid definitions. Removing these grid classes from the other modules, makes the panel for the epay module show "correctly".

Conclusion; there's nothing wrong with how this module renders the panel.
