### ISSUE TITLE
Mobilepay makes a double order

### ISSUE THREAD

**Issue by bulldesign** [ePay/prestashop#14]
Payment with mobilepay makes a double order. Tested on several shops, and same always makes a double order.

**Comment by AllanWLie** [comment]
Hi @bulldesign 
We have tested your issue, and we can not replicate it.

**Comment by Mreker** [comment]
I have same problem as bulldesign.

**Comment by bulldesign** [comment]
@Mreker There is definitely a problem, either from ePay or from the MobilePay integration. However i solved it by marking "Use own receipt" to No/Nej
http://prntscr.com/enicol

**Comment by Mreker** [comment]
Thank you @bulldesign for you reply. I want to use my own receipt, but I solved the problem temporary but rolling back to v4.9.4. I think the bug appear in v4.9.5+

**Comment by bulldesign** [comment]
@Mreker You can still use your own receipt (order-confirmation). as i can see, the only thing this function does is that it makes ePay give you a summary before you are redirected to the prestashop order confirmation.

**Comment by Mreker** [comment]
"Use own receipt" to No/Nej did not solve the problem for me. I still get double orders.

**Comment by taelpl** [comment]
Had similar issue on module -> solved by adding extra waiting time on the return so that the order will had time to be created.

**Comment by Mreker** [comment]
@taelpl Thank you. I am not sure how to make this change, can you tell me what file and the new value?

**Comment by AllanWLie** [comment]
@Mreker 
You will have to change the "10" value to something higher, on this line
https://github.com/ePay/prestashop/blob/master/epay/controllers/front/validation.php#L30

**Comment by Casper-O** [comment]
Its been a while since i Updated our epay module, but this loop for 10 secs or more. Is it really the right thing to do?

What we did was setting instantcallback to 0 (default is 1). Since then we had no issues with orders failed or double...

**Comment by Mreker** [comment]
Thank you @AllanWLie, What should I change the value to?

Or should I better set the instantcallback to 0?

**Comment by Casper-O** [comment]
Regarding instantCallback - I do not know if this will work with the most recent version, since it seems like we are now waiting for the callback to create the order.

**Comment by AllanWLie** [comment]
In the newest version, the accepturl also tries to create the order if the callback takes more that 10 seconds.
On normal transactions, this solution works but on mobile pay transactions there can be a concurrency issue. 

A possible solution to this is to set the timer to a value between 10 and 20 on this line:
https://github.com/ePay/prestashop/blob/master/epay/controllers/front/validation.php#L30

This will in the worst scenario cause your customers to wait 20 seconds before the payment window closes. 

We are looking into another solution which will come in a future release together with Prestashop 1.7 support.

-Allan

**Comment by bulldesign** [comment]
Even with all these fixes, it is actually still making double orders. Any update on a module that can actually handle mobilepay?

**Comment by Mreker** [comment]
I agree with bulldesign, the problem is still not solved.

**Comment by Casper-O** [comment]
I have not tested this, but my suggestion is that you try to comment out this wait for callback:
https://github.com/ePay/prestashop/blob/master/epay/controllers/front/validation.php#L28-L37

And on this line insert this:
`$parameters["instant_callback"]  = 0;`
https://github.com/ePay/prestashop/blob/master/epay/epay.php#L915

I guess this setup do require that you have set ownreceipt to 1 so the accept_url generates the order, before the callback do it.

This have solved issues we had before where we had before, dont know if this will solve yours.

Test it on own risk.

**Comment by bulldesign** [comment]
@Casper-O You say you didn't test the suggestion, but that it solved your issue? So i guess you did test it or?

Anyway..
I decided to jump back to the 4.8 version which worked like a charm and still does. 4.8 works fine with MobilePay with no double orders.

**Comment by jonathanparisi** [comment]
We have this issue too! We use prestashop 1.6.1.4 with multistore, ePay v.4.8

**Comment by bulldesign** [comment]
@jonathanparisi have you ticked "Use own receipt" to No ?

**Comment by AllanWLie** [comment]
We have now released a new version of the module which should handle this issue. The new version can be found here: https://github.com/ePay/prestashop/releases/latest
