### ISSUE TITLE
PrestaShop 1.7 compatibility?

### ISSUE THREAD

**Issue by wiruzman** [ePay/prestashop#17]
Hi,

Will there be compatibility for version 1.7?

**Comment by AllanWLie** [comment]
We are currently working on it.

**Comment by wiruzman** [comment]
I have build my own :)

**Comment by AllanWLie** [comment]
Cool, 

We have now launched our new version with 1.7.x support. Check it out here: https://github.com/ePay/prestashop/releases/latest

**Comment by wiruzman** [comment]
This is very good, I have deleted my repo and used yours which is officially supported when I need help :D

Thus, I have made a bug fix and created a pull request.
