### ISSUE TITLE
Mobilepay status issues

### ISSUE THREAD

**Issue by bulldesign** [ePay/prestashop#19]
The issue about double orders is solved, but a new issue with mobilepay appeared after installing the new version.

All Mobilepay orders with the new module are making problems with statuses at the moment - no status is assigned to the order. Also you cannot see what has been ordered. Not in the order page nor on the invoice.

Can anyone confirm this happens too with the new version?

PS version: 1.6.1.6

**Comment by Mreker** [comment]
Try to delete the module, clear cache and install it again.

I have no problems with the new module, and I am on same version as you.

**Comment by AllanWLie** [comment]
Hi @bulldesign 

If your issue still exists after doing what @Mreker wrote, then please write to support@bambora.com and tell them your issue.

Thank you @Mreker for helping @bulldesign 

Btw. a new version have just been released (v.5.0.1)
