### ISSUE TITLE
I nogle tilfælde laves der ikke en række i ps_epay_transactions

### ISSUE THREAD

**Issue by dennisdrejer** [ePay/prestashop#2]
Hej

Jeg har fundet ud af at i forhold til enkelte ordrer betalt via epay bliver der ikke lavet en linje i tabellen ps_epay_transactions. Dette gør at det ikke er muligt at hæve ordren via administrations interfacet.

Er det en fejl I er bekendt med og evt. har et fix til?

**Comment by dennisdrejer** [comment]
River lige op i denne igen. Jeg har stadigvæk problemet.

Du skrev " så kan det være et andet modul, som bliver eksekveret efter ordreoprettelsen, men før ePay modulet."

I hvilket hook skal jeg kigge efter dette?

**Comment by ePayMichael** [comment]
Jeg mener, at det er orderConfirmation.
Hvis der sker en fejl på følgende linje, så bliver transaktionen aldrig gemt:
https://github.com/ePay/prestashop/blob/master/epay/controllers/front/validation.php#L57

Men se den seneste pull request:
https://github.com/ePay/prestashop/pull/8

Måske den kan afhjælpe problemet.

**Comment by dennisdrejer** [comment]
Det ser ud til at jeg bruger en ældre version. Mit epay modul er ikke hooket up på orderconfirmation.

**Comment by dennisdrejer** [comment]
Der er kun disse i koden:
!$this->registerHook('payment') OR !$this->registerHook('rightColumn') OR !$this->registerHook('adminOrder') OR !$this->registerHook('paymentReturn') OR !$this->registerHook('footer')

**Comment by dennisdrejer** [comment]
Er det noget du har et bud på hvad jeg kan gøre ved?

**Comment by sorenla** [comment]
Det skulle være løst per version 4.9.0 af ePay modulet. Prøv [seneste release](https://github.com/ePay/prestashop/releases/latest) hvis ikke det er lykkedes dig at finde en løsning tidligere.
