### ISSUE TITLE
Valuta

### ISSUE THREAD

**Issue by Mokk** [ePay/prestashop#21]
Om det er euro, svenske kroner eller danske, så står der altid "kr" ved autoriseret beløb og hævet beløb.

**Comment by AllanWLie** [comment]
Hej @Mokk 
På order siden bruger vi den indbyggede funktion (Tools::displayPrice()) til at vise beløbet inkl. valuta symbolet. 

Denne funktion bruger de valuta  indstillinger som du har defineret i din Prestashop opsætning.

Mvh. Allan
