### ISSUE TITLE
"Invalid merchantnumber"

### ISSUE THREAD

**Issue by hjaltels** [ePay/prestashop#22]
Får meddelelsen "Invalid merchantnumber", selvom det er det helt rigtige nummer der er brugt. Burger version 1.6.1.14, hvor epay kører igennem Onepagecheckout modulet. Håber i kan hjælpe :)

ps. Havde også en kunde der i dag fik fejlmeldingen "error påfør betalingsadresse" på hans iPad, selvom alle felterne var udfyldt.

**Comment by AllanWLie** [comment]
Hej @hjaltels 

For at få hjælp til den konkrete sag, oprette en support ticket ved at skrive en mail til support@bambora.com og beskrive dit problem. Husk at medsend dine kunde informationer.

Kan du have en god dag.
