### ISSUE TITLE
Capture on more than one status

### ISSUE THREAD

**Issue by Casper-O** [ePay/prestashop#23]
If you also allow customers to pickup orders at your store, it would be nice to be able to capture money on more than one status, fx:
- Shipped
- Picked up at store

**Comment by AllanWLie** [comment]
Hej @Casper-O,
Muligheden for at vælge flere statusser for capture er ikke noget vi implementere lige nu. Men vi har skrevet det i vores backlog så muligvis kommer det engang i fremtiden. Du er selvfølgelig velkommen til at lave en pull request med den ønskede funktionalitet.  

Kan du have en god dag

-Allan
