### ISSUE TITLE
Payment request wrong amount

### ISSUE THREAD

**Issue by Casper-O** [ePay/prestashop#24]
Make an order in worth more than 1000 DKK, and save it as a order. Then send a payment request to the customer...
Test Case: order value: 1 568.00 DKK
Payment request recived: 1,57 DKK

**Comment by Casper-O** [comment]
please see #25 or #26 - both solutions should sort out the issue.

**Comment by AllanWLie** [comment]
Hej @Casper-O 

Vi har lige nu, lagt en ny release af modulet op, som indeholder en fix til beløbet i payment request.
https://github.com/ePay/prestashop/releases/latest
