### ISSUE TITLE
no payment option on checkout

### ISSUE THREAD

**Issue by thbl** [ePay/prestashop#27]
Installed on prestashop 1.7.2 with this settings
![settings](https://user-images.githubusercontent.com/19774996/32098825-3f8a8d50-bb0e-11e7-985c-ea2d8255c301.PNG)

But on checkout there is no option for ePay
![checkout](https://user-images.githubusercontent.com/19774996/32098863-5b9ccb52-bb0e-11e7-808d-2eb28ddf4f09.PNG)

**Comment by AllanWLie** [comment]
Hi @thbl 
Did you enable the module ?
![image](https://user-images.githubusercontent.com/7969203/33075559-35cf344e-ceca-11e7-9824-bc94b19439ff.png)
