### ISSUE TITLE
Wrong amount with discount

### ISSUE THREAD

**Issue by Killerzheka** [ePay/prestashop#28]
If we have discount for order, it is not accounted
![3](https://user-images.githubusercontent.com/24565216/34723356-eddde068-f552-11e7-88e2-f211eb11148a.png)
![4](https://user-images.githubusercontent.com/24565216/34723361-f334700e-f552-11e7-865b-a917e4bdb6fa.png)
Problem with:
epay.php:1065 -
$amount = ((string)($transaction["amount"] + $transaction["transfee"]));
need replace to
$full_amount = explode('.', $order->total_paid);
$amount = $full_amount[0].substr($full_amount[1],0,2);

**Comment by AllanWLie** [comment]
Hi @Killerzheka ,

Thank you for reporting this bug. 

What version of Prestashop and the module are you using? 

Best regards
Allan

**Comment by AllanWLie** [comment]
Hi @Killerzheka 

We have now testet your reported issue and we can not replicate your issue. 
When we use discount / coupons the amount is handled correctly.

The code block you are refering is for the "automated" capture on order status change. This function takes the authorized amount and captures it. This is working as intended. 

Have a nice day.

Best regards
Allan
