### ISSUE TITLE
Installation på PretaShop 1.7.3.0 fejler

### ISSUE THREAD

**Issue by ecopos** [ePay/prestashop#29]
Jeg har forgæves prøvet på at installere version 5.0.4, 5.0.3 og 5.0.0 på PrestaShop 1.7.3.0. Når jeg prøver på at installere modulet kommer der bare en fejl om at modulet ikke kunne installeres og der ikke er nogen yderligere oplysninger og det er lige meget om jeg bruge upload funktionen eller selv prøver at overfører modulet via FTP og efterfølgende prøver på at installere det.

Hvis jeg dog med det samme efter fejlen har været der prøver at installere igen, så lykkedes det og jeg kan også godt lave konfigurationen, men det kommer ikke frem under Betalingsmåder i PrestaShop administrationen og diverse hooks er heller ikke sat. Ved selv at sætte et hook i footer kan jeg godt få vist betalingskort logoerne.

Dog virker selve betalingsmetoden stadig ikke og jeg kan samtidigt også se at ps_epay_transactions tabellen ikke er blevet oprettet i databasen.

Spørgsmålet er så bare om i kender til problemer med installation på netop version 1.7.3.0 af PrestaShop og hvad der kan være galt?

**Comment by AllanWLie** [comment]
Hej @ecopos 

Jeg har lige på vores test server installeret en helt ren Prestashop 1.7.3.0 og efterfølgende installeret vores modul v 5.0.4 og alt virker som det skal. Ingen fejl og betalinger går fint igennem.

Måden jeg installerede modulet på var via den indbyggede upload funktion hvor jeg i "Fil dialogen" valgte filen "epay-prestashop-v5.0.4.zip" downloaded her fra: https://github.com/ePay/prestashop/releases/download/v5.0.4/epay-prestashop-v5.0.4.zip

Kan det tænkes at du har valgt den forkerte ".zip" fil?

Med venlig hilsen
Allan - Bambora Online

**Comment by AllanWLie** [comment]
Hej igen Bo,

Hook'en du referer til må være denne https://github.com/ePay/prestashop/blob/master/epay/epay.php#L65

Vores modul understøtter versionerne 1.5, 1.6 og 1.7 af prestashop 

Hook'en du referer er til version 1.5 og 1.6 af Prestashop og findes derfor ikke i version 1.7. I Version 1.7 bruges denne 
https://github.com/ePay/prestashop/blob/master/epay/epay.php#L82

Vi har ikke oplevet nogen problemer ligende den du beskriver før og som jeg beskrev så lavede jeg en ren installation af lige netop din version af Prestashop 1.7 (1.7.3.0) og som beskrevet oplevede jeg ikke de samme udfordringer som dig. 

For at modulet kommer til at virker 100% efterhensigten må jeg opfordre dig til at installere det via. Prestashops egen installer (Upload osv.).

Du kan eventuelt prøve at:

**NB Husk at fjerne alt du allerede har lavet inden du går igang**
1) Unzippe vores modul
2) i filen epay.php fjerne denne linje
https://github.com/ePay/prestashop/blob/master/epay/epay.php#L65
3) zip filen igen (husk .zip formatet)
4) Prøv at installere module via Prestashop.

Med venlig hilsen
Allan
