### ISSUE TITLE
Google Analytics bug

### ISSUE THREAD

**Issue by mortenborg** [ePay/prestashop#3]
Koden 

< script type="text/javascript" >
_gaq.push(['_setDomainName', 'none']);
_gaq.push(['_setAllowLinker', true]);
< /script >

som indsættes i hookFooter giver fejl når man er skiftet fra den gamle Google Analytics kode over til den nye Universal Analytics kode.

Der bør nok laves et check om man kører det ene eller andet hvis koden overhovedet er relevant når man kører UA.

Har ikke researchet det nærmere, kan blot konstatere at man får en fejl i konsollen på hver eneste side visning som det er nu.

**Comment by AllanWLie** [comment]
Hi @mortenborg 

We have removed the support for Google analytic in our module.
