### ISSUE TITLE
Undefined index: attributes_small fejl på en prestashop 1.7.3.0 installation

### ISSUE THREAD

**Issue by borkerdk** [ePay/prestashop#30]
Hej

Vi er ved at gå online med en shop hvor vi bruger ePay v5.0.4 modulet. Vi har gennemført betalling med check og bank modulet, som virker fint.
Når vi vælger ePay som betaling og forsøger at gennemfører betalingen kommer følgende fejl:

ContextErrorException in epay.php line 1179:
Notice: Undefined index: attributes_small

Fejlen opstår uanset hvilken vare vi putter i kurven. 
Det er sikkert at i ikke får samme fejl på en ren installation med enkelt produkter. Men denne shop har en del vare og også mange med attributer. 

Kan i hjælpe med at beskrive hvad fejlen er?

MVH 
Bo Kehrenberg

**Comment by AllanWLie** [comment]
Hej @borkerdk 

Fejlen opstår fordi jeres produkter ikke indeholder attributten "attributes_small" som jeg mener er en kort beskrivelse. Vores kode burde håndtere dette og vi har ikke set det før. Dog så kan der altid opstå special cases. 
Vi fjerner denne linje i næste version af modilet så den ikke kan give problemer i fremtiden. I mellemtiden kan du i modulets konfiguration slå "Invoice lines" fra.

Med venlig hilsen
Allan - Bambora

**Comment by AllanWLie** [comment]
Hej igen,

Vi har nu fjernet kilden til den fejl du oplever. 

https://github.com/ePay/prestashop/releases/latest

-Allan
