### ISSUE TITLE
Fixed "DKK" currency in remote api window

### ISSUE THREAD

**Issue by bulldesign** [ePay/prestashop#31]
Bug: The currency symbol is always DKK regardless of the order currency.
Obviously it should be dynamic depending on the currency of the order.

![image](https://user-images.githubusercontent.com/16975198/40584787-8b7b0dee-61a7-11e8-96d2-c92f48bf9dbc.png)

**Comment by AllanWLie** [comment]
Hi @bulldesign 

It have now been resolved. see https://github.com/ePay/prestashop/releases/latest

Thank you for reporting this bug.

**Best regards**
Allan - Bambora
