### ISSUE TITLE
Default selection of Bambora ?

### ISSUE THREAD

**Issue by rbuelund** [ePay/prestashop#35]
When you only have Bambora as payment option - the radio button is not selected as default. Can this be changed ?
![image](https://user-images.githubusercontent.com/1399437/48718861-77ec1480-ec1c-11e8-94a8-7b9cb733c97b.png)

**Comment by MathiasReker** [comment]
You have to do this change in Prestashop core.

**Comment by MathiasReker** [comment]
This issue can be closed
