### ISSUE TITLE
Hævninger laver sjove øreafrundinger

### ISSUE THREAD

**Issue by dennisdrejer** [ePay/prestashop#6]
Jeg har et problem.
Engang i mellem sker der en fejl, så system øreafrunder nogle beløb på en eller anden måde.

Det beløb som vi har reseveret er 582,30 og der bliver hævet 582,29. Hvordan kan det ske?

Det er over det sidste stykke tid sket et par gange for os:

582,30  582,29
564,30  564,29
264,15  264,14
159,45  159,44
149,95  149,94
145,20  145,19
145,20  145,19
138,70  138,69
133,20  133,19
285,90  285,89
149,70  149,69

Det giver bøvl i regnskabet. Har du noget bud på hvor fejlen kan være?

**Comment by ePayMichael** [comment]
Der er et problem med SoapClient i PHP.
Det kan løses ved, at du retter denne:
https://github.com/ePay/prestashop/blob/master/epay/api.php#L13

til noget i denne stil:
$epay_params['amount'] = ((string)$amount);

**Comment by ePayMichael** [comment]
Du skal give den til SoapClient som en streng. SoapClient vil så caste denne til en integer.

Prøv at se dette lille eksempel:
```
<?php
$total = "582.30";

$amount = $total * 100; //amount is now type float
echo "Total: ";
echo $amount; //58230
echo "\n";

$amountToCapture = intval($amount); //convert to integer
echo "Wrong: ";
echo $amountToCapture; //58229
echo "\n";
echo "\n";
echo "OK: ";
$amountStr = (string)$amount; //cast float to string
$amountStrToCapture = intval($amountStr); //convert to integer
echo $amountStrToCapture; //58230
 ?>
```

**Comment by sorenla** [comment]
Løst i [seneste release](https://github.com/ePay/prestashop/releases/latest).
