### ISSUE TITLE
Feature Request: Log employee name on credit and delete action

### ISSUE THREAD

**Issue by Casper-O** [ePay/prestashop#69]
It would be nice if you could see what employee that at least have credited or deleted a payment from BO.

**Comment by AllanWLie** [comment]
Hi @Casper-O

I have added this to our backlog for as a feature request.

Thank you.

Best regards
Allan - Bambora

**Comment by sessan** [comment]
@Casper-O Hi! This is now part of the latest version: v.5.1.1. Thanks! 
Best regards
Jessica -Bambora
