### ISSUE TITLE
transaction_id mangler på payment efter gennemført betaling

### ISSUE THREAD

**Issue by MortenKL** [ePay/prestashop#7]
Efter betaling er gennemført, mangler Transaction ID, på ordrens payment linje.
Jeg har behov for at kunne få transaction_id fra ordrens payment, fordi jeg hæver beløbet eksternt 'remote' via ePay's API.
Jeg kan se i koden (/controllers/front/validation.php, linie 64) at man forsøger at sætte transaction_id på ordrens payment, men det har ingen effekt fordi payment ikke gemmes umiddelbart efter.
Hvis man indsætter følgende: ($payment[0]->save();) lige efter linie 65, vil det virke som jeg formoder det var tanken. Og man kan se Transaction ID på ordren.

![no transaction id](https://cloud.githubusercontent.com/assets/3610705/6450004/27624da2-c125-11e4-83fa-26e433dc1ad7.png)

**Comment by sorenla** [comment]
Hej MortenKL

Problemet er løst i [seneste release](https://github.com/ePay/prestashop/releases/latest) af ePay modulet :)
