### ISSUE TITLE
Payment Request email languages

### ISSUE THREAD

**Issue by Casper-O** [ePay/prestashop#70]
When sending out a payment request, the langauge of the email English.

How can we change this, to for example Danish? I know it is possible to do in ePay Adminstration, but seems like the request API lacks the option?

**Comment by AllanWLie** [comment]
Hi @Casper-O 

I have added this to our backlog for as a feature request.

Thank you.

Best regards
Allan - Bambora

**Comment by sessan** [comment]
@Casper-O Unfortunately the api as you say lacks this functionality so the email language cannot be set. We will not implement this at this time in ePay. 

Best Regards
Jessica  - Bambora

**Comment by sessan** [comment]
This is actually now solved in version 5.1.2, @Casper-O
