### ISSUE TITLE
Overlay not centered around screen

### ISSUE THREAD

**Issue by bulldesign** [ePay/prestashop#71]
By using the overlay feature, if the checkout page is long, then the overlay does not seem to appear on the center of the screen, but rather on the very top, which means a customer has to scroll up to see the overlay.

**Comment by AllanWLie** [comment]
Hi @bulldesign 

The design of the Overlay payment window have always aligned with the top of the page and it is not something we are planing on changing. 

Have a good day.

Best regards
Allan - Bambora

**Comment by bulldesign** [comment]
Makes no sense. Why don't you center the the window on the screen?
