### ISSUE TITLE
PaymentLogos: Refused to execute script

### ISSUE THREAD

**Issue by Casper-O** [ePay/prestashop#74]
Following error is visible in Google Chrome Console:

> Refused to execute script from 'https://relay.ditonlinebetalingssystem.dk/integration/PaymentLogos/PaymentLogos.aspx?merchantnumber=XXXXXX&logo=0&direction=2&padding=2&rows=1&divid=epay_payment_logo_block' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

I dont think its a issue with the module itself, but something must have changed in the paymentLogo API recently

**Comment by sessan** [comment]
@Casper-O Yes, this is an issue that is outside this module. We are working on getting this working again.

**Comment by sessan** [comment]
Hi, as you probably already noticed, this issue is now fixed and the logos are showing again.
